Tarea 5: vectores en numpy    Luis Adolfo Martínez Ortiz - 22000352

In [1]:
import numpy as np

## Ejercicio 1

en data science y programación científica es común necesitar vectores con valores dentro de cierto intervalo, pero con sub-intervalos internos con diference espaciamiento ,por ejemplo:

[0.  , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.7 , 0.8 , 0.9 , 1.  ]
       
El primer sub-intervalo incrementa de 0.1 en 0.1 , el segundo de 0.01 en 0.01 , y el tercero de 0.1 en 0.1 nuevamente.

Usando unicamente NumPy crea un vector de este tipo con el nombre xs .

**nota**: no es permitido usar ciclos, debe realizarse con operaciones "vectorizadas" de numpy

In [3]:
# tu codigo aqui (~ 5 lineas de codigo):
x1 = np.linspace(0,0.5,6) 
x2 = np.linspace(0.51,0.59, 9)
x3 = np.linspace(0.6,1,5)
xs = np.concatenate([x1,x2,x3])
print(xs)

[0.   0.1  0.2  0.3  0.4  0.5  0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58
 0.59 0.6  0.7  0.8  0.9  1.  ]


### Ejercicio 2

Para calcular la información de una distribución de probabilidad necesitamos calcular el producto entre la información de cada posible x y su probabilidad , cada uno de estos elementos nos indica cuanta incerteza aporta cada x a la entropía de la distribución. Crea una función que calcule esto, debe recibir un vector representando a la dist. de probabilidad y devoler otro vector con el termino de entropía para cada x. Por ejemplo:

calcular_entropia([0.25,0.75])

Debe resultar en :

[0.5    ,    0.31127812]

**Nota**: la entropía es la suma sobre estos valores, en este caso no calculamos la entropía,unicamente los termimos de su sumatoria. La entropía es:

$$S = -\sum_i^nP(x_{i})log_{2}P(x_{i})$$

In [4]:
def calcula_entropia(x):
    return -(x*np.log2(x))

c1 = [0.25,0.75]
print(calcula_entropia(c1))


[0.5        0.31127812]


In [5]:
### Ejercicio 3

In [6]:
def g(x):
    
    ganancia = (np.power(x,3) + 2.0*(np.power(x,2.0))+np.exp(0.0001*x) - np.sqrt(2.0*x))/50
    
    return ganancia
    
gastos = np.array([100,50,25,100])
ganancia = g(gastos)

print("Ganancias",ganancia)

Ganancias [20399.73735829  2599.82010025   337.37862871 20399.73735829]


se ha determinado también que hay costos asociados a la comunicación y relación con los clientes(llamadas,mensajes electrónicos,etc) y que estos también tienen alta correlación con el monto que estos gastan en su primer més siguiendo el modelo:
$$c(x) = (x^{2} + x + log (0.0001x)-\sqrt{0.54x})/100$$

Cree una función para calcular este modelo sobre valores de de gasto de nuevos clientes , y luego cree una función  **ganancia_neta(x,g,c)** donde:
* x = vector conteniendo los valores de gasto del primer mes para nuevos clientes.
* g = función que estima la ganancia en función de x
* c = función que estima el costo en función de x

La función realiza el calculo simple **g(x) - c(x)** , ya que es posible que los modelos cambien en el tiempo es común recibir como parámetro el modelo o modelos hijos de un modelo mas grande , en este caso eso se logra recibiendo como parámetro las funciones de ganancia y costo.

In [7]:
def costo_neto(x):
    costo = (np.power(x,2)+ x + np.log(x * 0.0001) - np.sqrt(0.54*x))/100
    return costo

def ganancia_neta(x,g,c):
    return g(x)-c(x)

x = np.array([100,50,25,100])
ganancia_n = ganancia_neta(x,g,costo_neto)

print("Resultado: ",ganancia_n)

Resultado:  [20298.85689469  2574.42504495   330.9752857  20298.85689469]


### Ejercicio 4 - Mode

Usando argmax crear una función mode(x) para calcular la moda de un vector x , esta función debe devolver una tupla de 2 elementos de la forma:

(valor,conteo)

**tip** investigar y auxiliarse de otras funciones de numpy y np.argmax, no olvidar trabajar todo vectorizado, sin ciclos.

In [8]:
def mode(x):
    ## tu codigo aqui (~ 3 lineas de codigo):
    numero, cantidad = np.unique(x, return_counts=True)
    moda = np.argmax(cantidad)
    return numero[moda], cantidad[moda]
print(mode([1,2,3,3,4,3,3,2,2,1,2,6,2]))

(2, 5)


### Ejercicio 5

crear una función para calcular la entropía  de una distribución de probabilidad representada como un vector.
$$S = -\sum_i^nP(x_{i})log_{2}P(x_{i})$$

**Nota**: a diferencia del ejercicio anterior donde solo calculamos los términos de la entropía, en este caso  si calculamos el valor completo de la entropía, que como mencionamos es una medida de incerteza en una distribución de probabilidad.

**recordatorio**: no usar ciclos solo operaciones vectorizadas.

In [9]:
def calcular_entropia(arr):
    sal = np.sum(arr*np.log2(arr)*-1)
    return sal 

In [10]:
calcular_entropia([0.25,0.75])

0.8112781244591328

**Ejercicio**: En ML usamos la entropía cruzada como una forma de medir que tan bueno es un modelo de variables discretas a través de comparar la distribución de probabilidad que el modelo produce o predice, vs la distribución de probabilidad real dada por los datos de entrenamiento.

Podemos ver el siguiente ejemplo que define la forma en que se calcula la entropía cruzada y nos muestra un caso específico:

<img src="https://image.slidesharecdn.com/publishintroductiontodeeplearninginpythonandmatlab1-160502102437/95/introduction-to-deep-learning-in-python-and-matlab-54-638.jpg?cb=1462185644">

En este caso interpretamos así: El problema consiste en un modelo o algoritmo de ML que debe producir un vector de 3 elementos indicando la probabilidad de que ciertos datos X pertenezcan a una de 3 categorías.

* El modelo de ML produce un vector que indica que estima un 70% de probabilidad de que se trate de la categoría 0, 20% de probabilidad de que se trate de la categoría 1 y 10% de que se trate de la categoría 2.
* Los datos reales nos dicen que se trataba de un caso donde con total certeza se sabe que se trata de la categoría 0
* La entropía cruzada(a calcular en el ejercicio) nos indica que tan buena es la estimación del modelo, una EC de 0 es un modelo perfecto(en este caso un modelo que predice 100% de prob para la clase 0)

**Nota** 
* Aun que para calcular la entropía usamos logaritmos en base 2, en ML para calcular la entropía cruzada se usa logaritmo natural ya que con este se cumple el proposito **estimar que tanto se alejan las predicciones del modelo de ML de los datos reales** y es comunmente mas rápido de calcular en la computadora.
* Ya que estamos trabajando con vectores que representan distribuciones de probabilidad , podemos toparnos con lo que se conoce como : **sparse vectors**(vectores donde la mayoría de elementos son 0), esto puede producir problemas ya que le logaritmo de 0 no esta definido, tu solución debe tomar en cuenta esto y evitar que devuelva "nan"

In [11]:
def cross_entropy(Y,Y_hat):
    ##tu codigo aqui (~ 1 lineas de codigo)
    return np.sum(Y*np.log(np.clip(Y_hat, 1e-12, None) ))
    

y  = np.array([1.0,0,0])
y_hat = np.array([0.7,0.2,0.1])

cross_entropy(y,y_hat)

-0.35667494393873245

### Ejercicio 7 - Normalizacion

crear una función que reciba como parámetro un vector x y calcule su magnitud o norma(euclidiana o L2) ,luego usarla para evaluar 2 vectores que representan los errores generados por 2 modelos de machine learning y concluir cual de los 2 modelos es mejor.

In [12]:
def magnitud(x):
    ## tu codigo aqui (~ 1 linea de codigo)
    return np.sum(np.power(x,2)) # raiz cuadrada

errores_modelo1 = np.array([1,2,1,2]) #
errores_modelo2 = np.array([0,1,1,2]) #

print(magnitud(errores_modelo1))
print(magnitud(errores_modelo2))

10
6


### Ejercicio 8

Usando la función del ejercicio anterior, crea otra función normalizar(x) que reciba de parámetro un vector x aplique normalización sobre este, el resultado debe ser un nuevo vector del tamaño de x cuya magnitud es igual a 1.0

In [13]:
def normalizar(x):
    ## tu codigo aqui (~ 3 linea de codigo)
    return x / magnitud(x) 
    

print(magnitud(normalizar(errores_modelo1)))
print(normalizar(errores_modelo2))

0.10000000000000002
[0.         0.16666667 0.16666667 0.33333333]


## Ejercicio 9 - Opoeradores logicos

dado el vector x, usar operadores lógicos sobre vectores y acceso a  elementos usando vectores booleanos , escribir un programa que calcule eun nuevo vector z conteniendo el valor absoluto de el vector x.

**nota** No se puede usar np.abs() ni ciclos

**tip** usar un vector booleano para saber que elementos son negativos y deben ser multiplicados por -1

In [14]:
x = np.linspace(-4,4,12)

## tu codigo aqui (~ 4 linea de codigo)
def custom_abs(x):
    t1 = x[x<0]*-1
    t2 = x[x>=0]
    return np.concatenate((t1,t2))

print(custom_abs(x))

[4.         3.27272727 2.54545455 1.81818182 1.09090909 0.36363636
 0.36363636 1.09090909 1.81818182 2.54545455 3.27272727 4.        ]


### Ejercicio 10 

Implementar la función:
$$h(x) = \begin{cases}0 & x< 0\\1 & 0<=x <=1\\0 & x> 1\end{cases}$$

Esta debe funcionar para vectores de cualquier tamaño x:

def h(x):

    ...

**nota** debe ser implementada sin ciclos o ifs 

In [16]:
def h(x):
    ## tu codigo aqui (~ 3 linea de codigo)
    x0 = x[x<0]*0
    x1 = x[(x >= 0) & (x < 1)]/x[(x >= 0) & (x < 1)]
    x2 = x[x > 1]*0
    res = np.concatenate((x0,x1,x2))
    ##
    return res

x = np.array([0.1,-2,0.5,5])
print(h(x))

[-0.  1.  1.  0.]


### Ejercicio 11 - select

Usando select implementar una función k(x) con la siguiente definición:
$$k(x) = \begin{cases}-x & x< 0\\x^{3}  &0<=x<1\\x^{2}  &1<=x<2\\4  &otherwise\end{cases}$$

In [18]:
def k(x):
    condi = [x<0,(x >= 0) & (x < 1),(x >= 1) & (x < 2)]
    oper = [x,x**3,x**2]
    Res = np.select(condi,oper,4)
    return Res

x = np.linspace(0,2.5,11)
print(x)
print(k(x))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5 ]
[0.       0.015625 0.125    0.421875 1.       1.5625   2.25     3.0625
 4.       4.       4.      ]


### Ejercicio 12 - piecewise

Investigar piecewise y:
*  Usarlo para implementar la función anterior de manera eficiente
*  Usar piscewise para implementar la función:

$$m(x) = \begin{cases}e^{2x} & x< 0\\1  &0<=x<1\\e^{1-x}  &x<=1\\\end{cases}$$

Nuevamente, sin utilizar ciclos ni ifs

def k(x):

    k = np.piecewise(x, [x<0,(x >= 0) & (x < 1),x>=1],[lambda x: np.power(np.e,2*x),1,lambda x: np.power(np.e,1-x)])
    return k

x = np.linspace(-1,2.5,15)
print(x)
print(k(x))

In [19]:
def k(x):

    res = np.piecewise(x, [x<0,(x >= 0) & (x < 1),x>=1],[lambda x: np.power(np.e,2*x),1,lambda x: np.power(np.e,1-x)])
    return res

x = np.linspace(-1,2.5,15)
print(x)
print(k(x))


[-1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.    1.25  1.5   1.75
  2.    2.25  2.5 ]
[0.13533528 0.22313016 0.36787944 0.60653066 1.         1.
 1.         1.         1.         0.77880078 0.60653066 0.47236655
 0.36787944 0.2865048  0.22313016]


### Proyección vectorial

$$\vec{P_{u,v}} =  \frac{\vec{u} . \vec{v}}{|\vec{v}|^{2}} . \vec{v}$$

Es función de proyectar un vector sobre otro y cubrirlo desde el extremos y saber en que punto se corta la recta perpendicular

### Ejemplo

In [33]:
def vector_proyectado(u,v):
    cos = np.power(magnitud(v),2)
    resultado = np.dot(np.dot(u,v) / cos , v)
    
    return resultado

u = [4,5]
v = [6,0]
print ("Poyeccion vector 1: ", vector_proyectado(u,v))


Poyeccion vector 1:  [0.11111111 0.        ]


Esto lo podemos utilizar para saber cuando un objeto intercepta al otro

### Producto cruz

In [32]:
x1 = [4, 1, 6]
x2 = [3, 2, 3]
np.cross(a,b)

array([-9,  6,  5])