Tarea 6 - Ejercicios finales numpy
### Luis Adolfo Martínez Ortíz  - 22000352

**Ejercicio**: Investigar y ejemplificar diferencias entre np.array y np.matrix

np.array puede representar datos com más de una dimensión (ndarray), mientras np.matriz solo de dos dimensiones que forma fias y columna que se utilizan mucho en Machine Learning, analisis de correlacion (matriz de correlación) y análisis exploratios

In [3]:
import numpy as np

In [22]:
# np.array de mas dos dimensions
arr = np.array([[[4, 3], [2, 1]], 
              [[2, 3], [1, 4]]])
print(arr)
print("Rango: ", np.ndim(arr))

[[[4 3]
  [2 1]]

 [[2 3]
  [1 4]]]
Rango:  3 3


In [31]:
#np.matriz
matriz = np.matrix([[5, 7, 9],[3,4,5],[4,5,6]])
print(matriz)
print("Rango: ", np.ndim(matriz))

[[5 7 9]
 [3 4 5]
 [4 5 6]]
Rango:  2


**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicación de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producirá una nueva matriz con el mismo número de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la función "sigmoid"(descrita a continuación) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamaño pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la función sigmoid. El resultado debe ser un tensor con el mismo número de filas que la matriz X y una sola columna(una predicción para cada fila de X.

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

In [32]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [33]:
H1_W = np.array([[0.25,-8],
                 [0.37,14]])
OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],
               [1,2]])

H1 = np.matmul(X,H1_W)
H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1


print(OL)

[[0.99995577]
 [0.99999332]]


### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [83]:
def neural_network(x):
  input_pesos = np.array([[0.712, 0.355, 0.268],
                   [0.112, 0.855, 0.468]])
  hidden = np.array([[0.116], [0.329], [0.708]])

  hidden_1 = sigmoid(np.matmul(x,input_pesos)) 
  output = sigmoid(np.matmul(hidden_1,hidden))

  return output


In [84]:
arr =  np.array([1,1])

resultado = neural_network(arr)
print(resultado)
print(A.shape)

[0.69269553]
(1,)


Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

In [77]:
def neural_network(X):
  input_peso = np.array([[0.712, 0.355, 0.268],
                   [0.112, 0.855, 0.468]])
  
  hidden = np.array([[0.116], [0.329], [0.708]])
  sig = sigmoid(np.matmul(X,input_peso)) 
  output = max(np.matmul(sig,hidden))
  return output

In [78]:
arr =  np.array([[1,1],
               [1,1]])

resultado= neural_network(arr)
print(resultado)
print(A.shape)

[0.81275154]
(1,)
